version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: testdb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: