apiVersion: v1
kind: Pod
metadata:
  name: db-app-pod
  labels:
    app: app
spec:
  containers:
    - name: db-app
      image: artemgoncharov3012/simple-db-app
      ports:
        - containerPort: 3002